In [1]:
from datetime import datetime
import matplotlib.dates as mdates
import pandas as pd
import matplotlib.pyplot as plt
import geopandas
import seaborn as sns
import numpy as np
from matplotlib.pyplot import text
from matplotlib.pyplot import figure
import os
import glob

In [2]:
#read the original data path
path = r'D:\UCL\Term3\tbx-flaring-shihao\data\well_event_to_flaring_v1\data\model_data' 
csv_files = glob.glob(os.path.join(path, "*.csv"))

In [3]:

csv_files

['D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1020_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1020_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1020_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1020_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1124_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1136_10_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1136_10_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1136_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1136_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1142_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1152_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1222_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1222_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1222_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1222_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1389_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1421_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1421_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1421_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1421_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1593_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1598_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1598_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1635_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_8_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\168_8_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\179_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1863_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1863_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1885_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_8_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_8_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_9_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\1887_9_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_10_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_10_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_11_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_11_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_4_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_4_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_5_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_5_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_6_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_6_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_7_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_7_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_8_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_8_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_9_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\190_9_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\19_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\19_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\19_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\19_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2027_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2027_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_2_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_3_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2117_3_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2319_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2319_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2411_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\2411_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_0_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_0_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_1_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_1_flaring.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_2_events.csv',
 'D:\\UCL\\Term3\\tbx-flaring-shihao\\data\\well_event_to_flaring_v1\\data\\model_data\\274_2_flaring.csv',

In [4]:
#merge 2 csv files (in one group) into one csv 
for index in range(186):  
    df_events = pd.read_csv(csv_files[2*index])
    df_flaring = pd.read_csv(csv_files[2*index+1])
    df_concat = pd.concat([df_events, df_flaring], axis=1)
    if pd.isnull(df_concat.iloc[-1]['api']):
        df_concat= df_concat.ffill()
    df_concat.to_csv(str(index)+'.csv')

In [5]:
# merge each group's csv to one file
path = r'D:\UCL\Term3\tbx-flaring-shihao\src\notebooks' 
csv_files = glob.glob(os.path.join(path, "*.csv"))
li = []
for file in csv_files:
    df = pd.read_csv(file, index_col=None, header=0)
    li.append(df)
df = pd.concat(li, axis=0, ignore_index=True)    
df.to_csv('final_data.csv')

In [2]:
# adding the non flared data into the dataset
path = r'D:\UCL\Term3\tbx-flaring-shihao\data\all_wellpad_events.csv' 
path2 = r'D:\UCL\Term3\tbx-flaring-shihao\src\notebooks\final_data.csv'
df_allpad = pd.read_csv(path)
df = pd.read_csv(path2)

In [3]:
df_allpad= df_allpad.drop_duplicates()
df_allpad_notf = df_allpad[pd.isnull(df_allpad['flare_t_start'])]

In [4]:
# now we have the all in one dataset 
df1 = pd.concat([df, df_allpad_notf], axis=0)
df1

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.1,Unnamed: 0,api,state,basin,subbasin,county,source,...,Y,spatial_group,t_diff,days_diffs,temporal_group,color,geom,wellpads_id,area_m2,pad_status
0,0.0,0.0,13.0,3502.0,4.210337e+09,Texas,Permian,NaN,Crane,NaN,...,3.705585e+06,1018.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN,NaN
1,1.0,1.0,14.0,3502.0,4.210337e+09,Texas,Permian,NaN,Crane,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,0.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,3.713956e+06,1040.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN,NaN
3,3.0,1.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,3.713893e+06,1040.0,4 days 22:24:00,4.0,0.0,#32a852,NaN,NaN,NaN,NaN
4,4.0,2.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,3.713849e+06,1040.0,5 days 00:06:00,5.0,0.0,#32a852,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2001,NaN,NaN,1016.0,90184.0,4.230136e+09,Texas,Permian,Delaware,Loving,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,0101000020110F0000C95CAE371A0166C1D71DAD70CEA3...,847326.0,22543.566424,4.0
2002,NaN,NaN,1017.0,90222.0,4.230136e+09,Texas,Permian,Delaware,Loving,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,0101000020110F0000C4C1615B1A0166C195109668C8A3...,847326.0,22543.566424,4.0
2003,NaN,NaN,1021.0,90189.0,4.230135e+09,Texas,Permian,Delaware,Loving,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,0101000020110F0000BC5A218A4D0366C1B8CC78AF38B2...,847979.0,8995.243387,4.0
2004,NaN,NaN,1022.0,90194.0,4.210335e+09,Texas,Permian,NaN,Crane,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,0101000020110F0000E2E5EF413FC965C13E360D63EA34...,35872.0,10534.117057,6.0
2005,NaN,NaN,1023.0,90196.0,4.230135e+09,Texas,Permian,Delaware,Loving,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,0101000020110F0000BBD430EB390966C1779616BFEE9C...,852073.0,21328.462262,4.0

In [6]:
# drop the features that not applicable in models
df_first_clean= df1.drop(columns = ['Unnamed: 0.3','Unnamed: 0.1','geom','source','operator_code',
                    'operator_name','wellpad_code','parent_operator_co','geometry'])

In [7]:
df_first_clean= df_first_clean.reset_index()

In [8]:

df_first_clean['Unnamed: 0'] = df_first_clean['Unnamed: 0'].astype(int)
df_first_clean

,index,Unnamed: 0.4,Unnamed: 0,api,state,basin,subbasin,county,tst_permit_date,tst_permit_published_date,...,X,Y,spatial_group,t_diff,days_diffs,temporal_group,color,wellpads_id,area_m2,pad_status
0,0,0.0,3502,4.210337e+09,Texas,Permian,NaN,Crane,2017-05-30,NaN,...,-1.143404e+07,3.705585e+06,1018.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN
1,1,1.0,3502,4.210337e+09,Texas,Permian,NaN,Crane,2017-05-30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,-1.158979e+07,3.713956e+06,1040.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN
3,3,3.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,-1.159002e+07,3.713893e+06,1040.0,4 days 22:24:00,4.0,0.0,#32a852,NaN,NaN,NaN
4,4,4.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,-1.158989e+07,3.713849e+06,1040.0,5 days 00:06:00,5.0,0.0,#32a852,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2721,2001,NaN,90184,4.230136e+09,Texas,Permian,Delaware,Loving,2022-01-24,2022-01-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,847326.0,22543.566424,4.0
2722,2002,NaN,90222,4.230136e+09,Texas,Permian,Delaware,Loving,2022-03-08,2022-03-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,847326.0,22543.566424,4.0
2723,2003,NaN,90189,4.230135e+09,Texas,Permian,Delaware,Loving,2021-12-07,2021-12-16 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,847979.0,8995.243387,4.0
2724,2004,NaN,90194,4.210335e+09,Texas,Permian,NaN,Crane,2022-02-09,2022-03-02 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35872.0,10534.117057,6.0
2725,2005,NaN,90196,4.230135e+09,Texas,Permian,Delaware,Loving,2022-01-21,2022-02-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,852073.0,21328.462262,4.0

In [16]:
# use only the fixed value for each well pad 
df_allpad_use = df_allpad.drop_duplicates()
df_allpad_use_1 = df_allpad_use.iloc[:,[1,2,23,25,36]]
df_allpad_use_1

      Unnamed: 0         api  wellpads_id       area_m2  pad_status
0          12853  4200347045     849499.0  51709.594324           3
1          88985  4222741729     870311.0  49525.601937           3
2           4488  4217338604     846740.0  46505.319584           3
3          31526  4231742516     184617.0  62422.813724           6
4          60478  4231742307     729529.0  22010.427150           6
...          ...         ...          ...           ...         ...
2001       90184  4230135767     847326.0  22543.566424           4
2002       90222  4230135848     847326.0  22543.566424           4
2003       90189  4230134603     847979.0   8995.243387           4
2004       90194  4210335187      35872.0  10534.117057           6
2005       90196  4230134597     852073.0  21328.462262           4

[1057 rows x 5 columns]

In [17]:
# merging well pad info with flaring info
df3=pd.merge(df,df_allpad_use_1, left_on=['Unnamed: 0','api'], right_on=['Unnamed: 0','api'],how = 'left')
df3

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.1,Unnamed: 0,api,state,basin,subbasin,county,source,...,X,Y,spatial_group,t_diff,days_diffs,temporal_group,color,wellpads_id,area_m2,pad_status
0,0,0.0,13.0,3502.0,4.210337e+09,Texas,Permian,NaN,Crane,NaN,...,-1.143404e+07,3.705585e+06,1018.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN
1,1,1.0,14.0,3502.0,4.210337e+09,Texas,Permian,NaN,Crane,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,-1.158979e+07,3.713956e+06,1040.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN
3,3,1.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,-1.159002e+07,3.713893e+06,1040.0,4 days 22:24:00,4.0,0.0,#32a852,NaN,NaN,NaN
4,4,2.0,697.0,76634.0,4.210933e+09,Texas,Permian,Delaware,Culberson,NaN,...,-1.158989e+07,3.713849e+06,1040.0,5 days 00:06:00,5.0,0.0,#32a852,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,1963,8.0,361.0,42198.0,4.232942e+09,Texas,Permian,Midland,Midland,tx_trrc_permit_master,...,-1.135915e+07,3.764283e+06,21.0,0 days 01:42:00,0.0,1.0,#5c62b5,NaN,NaN,NaN
1964,1964,0.0,363.0,56770.0,4.232942e+09,Texas,Permian,Midland,Midland,tx_trrc_permit_master,...,-1.135925e+07,3.764823e+06,21.0,63 days 00:18:00,63.0,4.0,#38a69e,NaN,NaN,NaN
1965,1965,1.0,363.0,56770.0,4.232942e+09,Texas,Permian,Midland,Midland,tx_trrc_permit_master,...,-1.135925e+07,3.764605e+06,21.0,0 days 23:42:00,0.0,4.0,#38a69e,NaN,NaN,NaN
1966,1966,0.0,701.0,78571.0,4.213544e+09,Texas,Permian,NaN,Ector,tx_trrc_permit_master,...,-1.143394e+07,3.774026e+06,2260.0,161 days 01:24:00,161.0,2.0,#e587e8,NaN,NaN,NaN
1967,1967,1.0,702.0,78572.0,4.213544e+09,Texas,Permian,NaN,Ector,tx_trrc_permit_master,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:

df3=pd.merge(df_first_clean,df_allpad_use_1, left_on=['Unnamed: 0','api'], right_on=['Unnamed: 0','api'],how = 'left')
df3

,index,Unnamed: 0.4,Unnamed: 0,api,state,basin,subbasin,county,tst_permit_date,tst_permit_published_date,...,spatial_group,t_diff,days_diffs,temporal_group,color,wellpads_id,area_m2_x,pad_status_x,area_m2_y,pad_status_y
0,0,0.0,3502,4.210337e+09,Texas,Permian,NaN,Crane,2017-05-30,NaN,...,1018.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN,NaN,NaN
1,1,1.0,3502,4.210337e+09,Texas,Permian,NaN,Crane,2017-05-30,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,1040.0,NaN,0.0,0.0,#32a852,NaN,NaN,NaN,NaN,NaN
3,3,3.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,1040.0,4 days 22:24:00,4.0,0.0,#32a852,NaN,NaN,NaN,NaN,NaN
4,4,4.0,76634,4.210933e+09,Texas,Permian,Delaware,Culberson,2016-06-24,NaN,...,1040.0,5 days 00:06:00,5.0,0.0,#32a852,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3903,2001,NaN,90184,4.230136e+09,Texas,Permian,Delaware,Loving,2022-01-24,2022-01-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,847326.0,22543.566424,4.0,22543.566424,4.0
3904,2002,NaN,90222,4.230136e+09,Texas,Permian,Delaware,Loving,2022-03-08,2022-03-26 00:00:00,...,NaN,NaN,NaN,NaN,NaN,847326.0,22543.566424,4.0,22543.566424,4.0
3905,2003,NaN,90189,4.230135e+09,Texas,Permian,Delaware,Loving,2021-12-07,2021-12-16 00:00:00,...,NaN,NaN,NaN,NaN,NaN,847979.0,8995.243387,4.0,8995.243387,4.0
3906,2004,NaN,90194,4.210335e+09,Texas,Permian,NaN,Crane,2022-02-09,2022-03-02 00:00:00,...,NaN,NaN,NaN,NaN,NaN,35872.0,10534.117057,6.0,10534.117057,6.0
3907,2005,NaN,90196,4.230135e+09,Texas,Permian,Delaware,Loving,2022-01-21,2022-02-01 00:00:00,...,NaN,NaN,NaN,NaN,NaN,852073.0,21328.462262,4.0,21328.462262,4.0

In [19]:
df3.to_csv('new_df.csv')

In [10]:
all_wellpad_events = pd.read_csv(r'D:\UCL\Term3\tbx-flaring-shihao\src\notebooks\new_df.csv')

In [11]:
all_wellpad_events

,Unnamed: 0,api,state,basin,subbasin,county,tst_permit_date,tst_permit_published_date,tst_spud_date,tst_completion_date,...,power,rad,source_id,aq_date,X,Y,spatial_group,t_diff,days_diffs,temporal_group
0,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.240971,0.447881,10274.0,2014/10/1 8:42,-11534776.46,3761261.780,1020.0,123 days 00:00:00,123.0,2.0
1,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.731796,0.384363,264828.0,2014/10/3 8:06,-11534631.23,3761452.030,1020.0,1 days 23:24:00,1.0,2.0
2,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.998371,0.413679,70994.0,2014/10/5 9:06,-11534471.57,3761133.364,1020.0,2 days 01:00:00,2.0,2.0
3,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.822643,0.408657,70994.0,2014/10/5 9:06,-11534586.22,3761263.032,1020.0,0 days 00:00:00,0.0,2.0
4,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.370339,0.395678,367190.0,2014/10/6 8:48,-11534660.11,3761204.205,1020.0,0 days 23:42:00,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2536,89875,4211533855,Texas,Permian,Midland,Dawson,2021/11/12,2021/12/2 0:00,2021/12/3,2022/3/9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2537,90172,4230135762,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/26 0:00,2022/3/11,2022/3/31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2538,90175,4230135766,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/30 0:00,2022/3/4,2022/3/26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2539,90183,4230135755,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/29 0:00,2022/3/16,2022/4/13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2540,90194,4210335187,Texas,Permian,NaN,Crane,2022/2/9,2022/3/2 0:00,2022/2/17,2022/3/15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# adding a pad status value for the model to know the status of pads 
def pad_status(row):
    
    pad_status = 0
    
    # Cascade down by lifecycle event to determine the pad status
    if pd.notnull(row['tst_first_detection_date']):  
        
        pad_status = 1 # Has detection
        
    if pd.notnull(row['tst_permit_date']):

        pad_status = 2 # Has Permit
 
    if pd.notnull(row['tst_spud_date']):

        pad_status = 3 # Has spud
            
    if pd.notnull(row['tst_completion_date']):

        pad_status = 4 # Has one completion confirmation

        if pd.notnull(row['tst_fracfocus_jobstart_date']):

            pad_status = 5 # Has two completion confirmations

            if pd.notnull(row['tst_fracfocus_jobend_date']):

                pad_status = 6 # Has three completion confirmations
        else:

            if pd.notnull(row['tst_fracfocus_jobend_date']):

                pad_status = 5 # Has two completion confirmations
        
            else:
                
                if pd.notnull(row['tst_fracfocus_jobstart_date']):
                    
                    pad_status = 4 # Has one completion confirmation
                
                    if pd.notnull(row['tst_fracfocus_jobend_date']):
                        
                        pad_status = 5 # Has two completion confirmations
                    
                else:
                    
                    if pd.notnull(row['tst_fracfocus_jobend_date']):
                        
                        pad_status = 4 # Has one completion confirmation                     
    
    return pad_status

    
all_wellpad_events['pad_status'] = all_wellpad_events.apply(pad_status, axis=1)

In [16]:
# save the df as final output dataset
all_wellpad_events = all_wellpad_events.drop_duplicates()
all_wellpad_events.to_csv('final_df.csv')
all_wellpad_events

,Unnamed: 0,api,state,basin,subbasin,county,tst_permit_date,tst_permit_published_date,tst_spud_date,tst_completion_date,...,rad,source_id,aq_date,X,Y,spatial_group,t_diff,days_diffs,temporal_group,pad_status
0,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.447881,10274.0,2014/10/1 8:42,-11534776.46,3761261.780,1020.0,123 days 00:00:00,123.0,2.0,4
1,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.384363,264828.0,2014/10/3 8:06,-11534631.23,3761452.030,1020.0,1 days 23:24:00,1.0,2.0,4
2,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.413679,70994.0,2014/10/5 9:06,-11534471.57,3761133.364,1020.0,2 days 01:00:00,2.0,2.0,4
3,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.408657,70994.0,2014/10/5 9:06,-11534586.22,3761263.032,1020.0,0 days 00:00:00,0.0,2.0,4
4,90222,4230135848,Texas,Permian,Delaware,Loving,2022/3/8,2022/3/26 0:00,2022/3/22,2022/4/18,...,0.395678,367190.0,2014/10/6 8:48,-11534660.11,3761204.205,1020.0,0 days 23:42:00,0.0,2.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2536,89875,4211533855,Texas,Permian,Midland,Dawson,2021/11/12,2021/12/2 0:00,2021/12/3,2022/3/9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2537,90172,4230135762,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/26 0:00,2022/3/11,2022/3/31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2538,90175,4230135766,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/30 0:00,2022/3/4,2022/3/26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2539,90183,4230135755,Texas,Permian,Delaware,Loving,2022/1/24,2022/1/29 0:00,2022/3/16,2022/4/13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2540,90194,4210335187,Texas,Permian,NaN,Crane,2022/2/9,2022/3/2 0:00,2022/2/17,2022/3/15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6