In [1]:
from datetime import datetime
import matplotlib.dates as mdates
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import os

In [2]:
# Prepare data for XG Boost


# For a given wellpad....

# how old is it in days? t = 1, day old pad, t=100 pad hundred days old
# what has already happened to it? events, flaring
# what is going to happen in the future? future flaring...

In [3]:
df = pd.read_csv(os.path.join('..','..', 'data', 'final_data', 'final_df_RNN.csv'))

columns = ['wellpad_code','area_m2', 'state', 'basin', 'subbasin', 'county', 'company_type',
           'tst_first_detection_date', 'tst_permit_date', 'tst_permit_published_date', 'tst_spud_date', 
           'tst_completion_date', 'tst_fracfocus_jobstart_date', 'tst_fracfocus_jobend_date',
           'wellpad_vintage_year', 'aq_date', 'power'] # temporal group is missing....

df1 = df[columns].copy()

def is_correct_dt(dt_str):
    
    try:
        dt = datetime.strptime(dt_str, '%Y/%m/%d')
    except:
        dt = np.nan
    
    return dt
    
df1['tst_first_detection_date'] = df1['tst_first_detection_date'].apply(is_correct_dt)

/home/sam/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3172: DtypeWarning: Columns (27,28,39,41,42,43,44,47,50,52) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
df1['aq_date'] = pd.to_datetime(df1['aq_date'], format='%Y%m%d %H:%M')
df1['tst_first_detection_date'] = pd.to_datetime(df1['tst_first_detection_date'], format='%Y/%m/%d')
df1['tst_permit_date'] = pd.to_datetime(df1['tst_permit_date'], format='%Y/%m/%d')
df1['tst_permit_published_date'] = pd.to_datetime(df1['tst_permit_published_date'], format='%Y/%m/%d')
df1['tst_spud_date'] = pd.to_datetime(df1['tst_spud_date'], format='%Y/%m/%d')
df1['tst_completion_date'] = pd.to_datetime(df1['tst_completion_date'], format='%Y/%m/%d')
df1['tst_fracfocus_jobstart_date'] = pd.to_datetime(df1['tst_fracfocus_jobstart_date'], format='%Y/%m/%d')
df1['tst_fracfocus_jobend_date'] = pd.to_datetime(df1['tst_fracfocus_jobend_date'], format='%Y/%m/%d')
df1['tst_fracfocus_jobend_date'] = pd.to_datetime(df1['tst_fracfocus_jobend_date'], format='%Y/%m/%d')

In [5]:
df1

,wellpad_code,area_m2,state,basin,subbasin,county,company_type,tst_first_detection_date,tst_permit_date,tst_permit_published_date,tst_spud_date,tst_completion_date,tst_fracfocus_jobstart_date,tst_fracfocus_jobend_date,wellpad_vintage_year,aq_date,power
0,9txqyd3v,20400.651830,Texas,Permian,Midland,Martin,Private,2018-05-06,2018-06-08,2018-06-10,2018-07-14,2019-04-28,2019-03-21 00:00:00,2019-04-11 00:00:00,2018,2019-07-03 07:42:00,2.53
1,9txqydx8,35254.991310,Texas,Permian,Midland,Martin,Private,2020-09-17,2020-09-21,2020-09-23,2021-05-18,2022-02-09,2022-01-04 18:33:00,2022-01-17 03:08:00,2021,2022-04-04 07:31:00,1.62
2,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,Private,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-04 08:22:00,1.78
3,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,Private,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-04 09:13:00,0.79
4,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,Private,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-06 19:04:00,5.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154112,9tz7mnen,14609.213250,Texas,Permian,Midland,Dawson,Private,NaT,2022-02-07,2022-02-14,2022-03-12,2022-06-10,2022-05-25 11:01:00,2022-05-25 11:50:00,2022,NaT,NaN
154113,9trx874v,7889.643735,Texas,Permian,NaN,Pecos,Public,NaT,2021-12-15,2021-12-20,2022-03-04,2022-03-11,NaT,NaT,2022,NaT,NaN
154114,9trx86q0,6531.521689,Texas,Permian,NaN,Pecos,Public,NaT,2021-12-21,2021-12-28,2022-03-11,2022-03-22,NaT,NaT,2022,NaT,NaN
154115,9twm9n10,19650.933560,Texas,Permian,Delaware,Loving,Public,NaT,2021-12-07,2021-12-09,2022-05-28,2022-06-28,NaT,NaT,2022,NaT,NaN
154116,9twmu0eg,25507.269360,Texas,Permian,Delaware,Loving,Private,NaT,2022-03-24,2022-04-01,2022-04-22,2022-05-06,NaT,NaT,2022,NaT,NaN

In [6]:
def public_private_class(company_type):
    
    ctype_class = 0
    if company_type == 'Public':
        ctype_class = 1
        
    return ctype_class

df1['company_type'] = df1['company_type'].apply(public_private_class)

In [7]:
# Find minimum date
sub_df = df1[['tst_first_detection_date', 'tst_permit_date','tst_permit_published_date','tst_spud_date','tst_completion_date','tst_fracfocus_jobstart_date',
             'tst_fracfocus_jobend_date']].copy()
sub_df['t0'] = sub_df.min(axis = 1)
df1['t0'] = sub_df['t0']

# Find mminimum date

sub_df = df1[['tst_first_detection_date', 'tst_permit_date','tst_permit_published_date','tst_spud_date','tst_completion_date','tst_fracfocus_jobstart_date',
             'tst_fracfocus_jobend_date', 'aq_date']].copy()
sub_df['tmax'] = sub_df.max(axis = 1)

df1['tmax'] = sub_df['tmax']

In [8]:
df1

,wellpad_code,area_m2,state,basin,subbasin,county,company_type,tst_first_detection_date,tst_permit_date,tst_permit_published_date,tst_spud_date,tst_completion_date,tst_fracfocus_jobstart_date,tst_fracfocus_jobend_date,wellpad_vintage_year,aq_date,power,t0,tmax
0,9txqyd3v,20400.651830,Texas,Permian,Midland,Martin,0,2018-05-06,2018-06-08,2018-06-10,2018-07-14,2019-04-28,2019-03-21 00:00:00,2019-04-11 00:00:00,2018,2019-07-03 07:42:00,2.53,2018-05-06,2019-07-03 07:42:00
1,9txqydx8,35254.991310,Texas,Permian,Midland,Martin,0,2020-09-17,2020-09-21,2020-09-23,2021-05-18,2022-02-09,2022-01-04 18:33:00,2022-01-17 03:08:00,2021,2022-04-04 07:31:00,1.62,2020-09-17,2022-04-04 07:31:00
2,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-04 08:22:00,1.78,2020-08-13,2022-04-04 08:22:00
3,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-04 09:13:00,0.79,2020-08-13,2022-04-04 09:13:00
4,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15 06:00:00,2021-12-31 06:00:00,2020,2022-04-06 19:04:00,5.49,2020-08-13,2022-04-06 19:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154112,9tz7mnen,14609.213250,Texas,Permian,Midland,Dawson,0,NaT,2022-02-07,2022-02-14,2022-03-12,2022-06-10,2022-05-25 11:01:00,2022-05-25 11:50:00,2022,NaT,NaN,2022-02-07,2022-06-10 00:00:00
154113,9trx874v,7889.643735,Texas,Permian,NaN,Pecos,1,NaT,2021-12-15,2021-12-20,2022-03-04,2022-03-11,NaT,NaT,2022,NaT,NaN,2021-12-15,2022-03-11 00:00:00
154114,9trx86q0,6531.521689,Texas,Permian,NaN,Pecos,1,NaT,2021-12-21,2021-12-28,2022-03-11,2022-03-22,NaT,NaT,2022,NaT,NaN,2021-12-21,2022-03-22 00:00:00
154115,9twm9n10,19650.933560,Texas,Permian,Delaware,Loving,1,NaT,2021-12-07,2021-12-09,2022-05-28,2022-06-28,NaT,NaT,2022,NaT,NaN,2021-12-07,2022-06-28 00:00:00
154116,9twmu0eg,25507.269360,Texas,Permian,Delaware,Loving,0,NaT,2022-03-24,2022-04-01,2022-04-22,2022-05-06,NaT,NaT,2022,NaT,NaN,2022-03-24,2022-05-06 00:00:00

In [9]:
# Convert everything to standard dates

df1['aq_date'] = pd.to_datetime(df1['aq_date']).dt.date
df1['tst_first_detection_date'] = pd.to_datetime(df1['tst_first_detection_date']).dt.date
df1['tst_permit_date'] = pd.to_datetime(df1['tst_permit_date']).dt.date
df1['tst_permit_published_date'] = pd.to_datetime(df1['tst_permit_published_date']).dt.date
df1['tst_spud_date'] = pd.to_datetime(df1['tst_spud_date']).dt.date
df1['tst_completion_date'] = pd.to_datetime(df1['tst_completion_date']).dt.date
df1['tst_fracfocus_jobstart_date'] = pd.to_datetime(df1['tst_fracfocus_jobstart_date']).dt.date
df1['tst_fracfocus_jobend_date'] = pd.to_datetime(df1['tst_fracfocus_jobend_date']).dt.date
df1['tst_fracfocus_jobend_date'] = pd.to_datetime(df1['tst_fracfocus_jobend_date']).dt.date
df1['t0'] = pd.to_datetime(df1['t0']).dt.date
df1['tmax'] = pd.to_datetime(df1['tmax']).dt.date

In [10]:
df1

,wellpad_code,area_m2,state,basin,subbasin,county,company_type,tst_first_detection_date,tst_permit_date,tst_permit_published_date,tst_spud_date,tst_completion_date,tst_fracfocus_jobstart_date,tst_fracfocus_jobend_date,wellpad_vintage_year,aq_date,power,t0,tmax
0,9txqyd3v,20400.651830,Texas,Permian,Midland,Martin,0,2018-05-06,2018-06-08,2018-06-10,2018-07-14,2019-04-28,2019-03-21,2019-04-11,2018,2019-07-03,2.53,2018-05-06,2019-07-03
1,9txqydx8,35254.991310,Texas,Permian,Midland,Martin,0,2020-09-17,2020-09-21,2020-09-23,2021-05-18,2022-02-09,2022-01-04,2022-01-17,2021,2022-04-04,1.62,2020-09-17,2022-04-04
2,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15,2021-12-31,2020,2022-04-04,1.78,2020-08-13,2022-04-04
3,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15,2021-12-31,2020,2022-04-04,0.79,2020-08-13,2022-04-04
4,9txqyf9e,31574.652690,Texas,Permian,Midland,Martin,0,2020-08-13,2020-09-14,2020-09-23,2020-10-15,2022-02-09,2021-12-15,2021-12-31,2020,2022-04-06,5.49,2020-08-13,2022-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154112,9tz7mnen,14609.213250,Texas,Permian,Midland,Dawson,0,NaT,2022-02-07,2022-02-14,2022-03-12,2022-06-10,2022-05-25,2022-05-25,2022,NaT,NaN,2022-02-07,2022-06-10
154113,9trx874v,7889.643735,Texas,Permian,NaN,Pecos,1,NaT,2021-12-15,2021-12-20,2022-03-04,2022-03-11,NaT,NaT,2022,NaT,NaN,2021-12-15,2022-03-11
154114,9trx86q0,6531.521689,Texas,Permian,NaN,Pecos,1,NaT,2021-12-21,2021-12-28,2022-03-11,2022-03-22,NaT,NaT,2022,NaT,NaN,2021-12-21,2022-03-22
154115,9twm9n10,19650.933560,Texas,Permian,Delaware,Loving,1,NaT,2021-12-07,2021-12-09,2022-05-28,2022-06-28,NaT,NaT,2022,NaT,NaN,2021-12-07,2022-06-28
154116,9twmu0eg,25507.269360,Texas,Permian,Delaware,Loving,0,NaT,2022-03-24,2022-04-01,2022-04-22,2022-05-06,NaT,NaT,2022,NaT,NaN,2022-03-24,2022-05-06

In [11]:
# Simulate Daily Time series per wellpad

wellpad_groups = df1.groupby('wellpad_code')

In [12]:
def flare_check(rows, todays_date):

    todays_date = todays_date.date()
    
    is_flaring = 0
    flares_n = 0 # Number of flares so far
    flares_power = 0 # Total FRP so far
    t_until_next_flare = np.nan # Time until next flaring event
    t_since_last_flare = np.nan # Time since last flare event
    flares_future_n = 0 # Number of flares in the future
    flares_future_power = 0 # Total FRP in the future
    
    rows_today_and_before = rows.loc[rows['aq_date'] <= todays_date] # Get rows today and before
    rows_future = rows.loc[rows['aq_date'] > todays_date] # Get future rows
    
    
    if len(rows_today_and_before) > 0: # Do we have any flaring data today or before?
        
        flares_n = len(rows_today_and_before)
        flares_power = rows_today_and_before.power.sum()
        most_recent_flare = rows_today_and_before.sort_values('aq_date', ascending=False).head(1)
        t_since_last_flare = (todays_date-most_recent_flare['aq_date'].values[0]).days
        
        if (todays_date ==  most_recent_flare['aq_date'].values[0]):
            is_flaring = 1
        
    if len(rows_future) > 0: # Do we have any flaring data after today?
        
        flares_future_n = len(rows_future)
        flares_future_power = rows_future.power.sum()
        next_flare = rows_future.sort_values('aq_date', ascending=True).head(1)
        t_until_next_flare = (next_flare['aq_date'].values[0]-todays_date).days


    return flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring
    
    
def spud_check(rows, todays_date):

    # Get first row
    row = rows.head(1)
    
    t_spud_diff = np.nan
    
    spud_date = row['tst_spud_date'].values[0]
    todays_date = todays_date.date()
    
    if spud_date is not pd.NaT:
        if spud_date <= todays_date:

            t_spud_diff = (todays_date-spud_date).days
            
    return t_spud_diff


def completion_check(rows, todays_date):
    
    # Get first row
    row = rows.head(1)
    
    n_completions = 0
    t_comp_diff = np.nan
    
    comp_diffs = []
    
    todays_date = todays_date.date()
    
    tst_completion_date = row['tst_completion_date'].values[0]
     
    if tst_completion_date is not pd.NaT:
        if tst_completion_date <= todays_date:
            
            n_completions+=1
            
            comp_diffs.append((todays_date-tst_completion_date).days)
    
    
    
    tst_fracfocus_jobstart_date = row['tst_fracfocus_jobstart_date'].values[0]
    
    if tst_fracfocus_jobstart_date is not pd.NaT:
        if tst_fracfocus_jobstart_date <= todays_date:
            
            n_completions+=1
            
            comp_diffs.append((todays_date-tst_fracfocus_jobstart_date).days)

            
            
    tst_fracfocus_jobend_date = row['tst_fracfocus_jobend_date'].values[0]
    
    if tst_fracfocus_jobend_date is not pd.NaT:
        if tst_fracfocus_jobend_date <= todays_date:
            
            n_completions+=1
            
            comp_diffs.append((todays_date-tst_fracfocus_jobend_date).days)
      
    
    if len(comp_diffs) > 0:
        t_comp_diff = min(comp_diffs)
        
    return n_completions, t_comp_diff

In [14]:
from tqdm.notebook import tqdm
from multiprocessing import Pool


group_inc = 0

group_keys = list(wellpad_groups.groups.keys())

def process_wellpad_events(idx):
    
    rows = wellpad_groups.get_group(group_keys[idx])
    
    wellpad_code = group_keys[idx]
    
    # Fixed variables
    company_type = rows['company_type'].values[0]
    area_m2 = rows['area_m2'].values[0]
    state = rows['state'].values[0]
    basin = rows['basin'].values[0]
    subbasin = rows['subbasin'].values[0]
    county = rows['county'].values[0]
    wellpad_vintage_year = rows['wellpad_vintage_year'].values[0]


    # Interpolate and cycle through all possible days between t0 and tmax

    t0 = rows['t0'].values[0] # Where we start daily increments
    tmax = rows['tmax'].values[0] # Where we end daily increments

    t_inc = 0 # What day we are on relative to t0
    delta = tmax - t0
    n_days = delta.days # Number of days in this wellpad sample
        
    # Define columns and prepopulate rows for n_days
    t_n_col = np.empty(n_days, dtype=np.uint16)
    company_type_col =  np.empty(n_days, dtype=np.uint8)
    area_m2_col =  np.empty(n_days, dtype=np.float32)
    state_col =  np.empty(n_days, dtype=object)
    basin_col =  np.empty(n_days, dtype=object)
    subbasin_col =  np.empty(n_days, dtype=object)
    county_col =  np.empty(n_days, dtype=object)
    wellpad_vintage_year_col = np.empty(n_days, dtype=np.uint16)
    flares_n_col =  np.empty(n_days, dtype=np.uint8)
    flares_power_col =  np.empty(n_days, dtype=np.float32)
    n_completions_col =  np.empty(n_days, dtype=np.uint8)
    t_comp_diff_col =  np.empty(n_days, dtype=np.float32)
    t_spud_diff_col =  np.empty(n_days, dtype=np.float32)
    is_flaring_col =  np.empty(n_days, dtype=np.uint8)
    t_until_next_flare_col =  np.empty(n_days, dtype=np.float32)
    t_since_last_flare_col =  np.empty(n_days, dtype=np.float32)
    flares_future_n_col =  np.empty(n_days, dtype=np.float32)
    flares_future_power_col = np.empty(n_days, dtype=np.float32)

    for n in range(0, int(n_days)+1):
        
        todays_date = t0+pd.DateOffset(days=n)

        flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring = flare_check(rows, todays_date)

        t_spud_diff = spud_check(rows, todays_date)
        n_completions, t_comp_diff = completion_check(rows, todays_date)

        t_n_col[n-1] = n
        company_type_col[n-1] = company_type
        area_m2_col[n-1] = area_m2
        state_col[n-1] = state
        basin_col[n-1] = basin
        subbasin_col[n-1] = subbasin
        county_col[n-1] = county
        wellpad_vintage_year_col[n-1] = wellpad_vintage_year
        flares_n_col[n-1] = flares_n
        flares_power_col[n-1] = flares_power
        n_completions_col[n-1] = n_completions
        t_comp_diff_col[n-1] = t_comp_diff
        t_spud_diff_col[n-1] = t_spud_diff
        is_flaring_col[n-1] = is_flaring
        t_until_next_flare_col[n-1] = t_until_next_flare
        t_since_last_flare_col[n-1] = t_since_last_flare
        flares_future_n_col[n-1] = flares_future_n
        flares_future_power_col[n-1] = flares_future_power

    wellpad_daily_event_df = pd.DataFrame({
        't_n': t_n_col,
        'company_type': company_type_col,
        'area_m2': area_m2_col,
        'state': state_col,
        'basin': basin_col,
        'subbasin':subbasin_col,
        'county': county_col,
        'wellpad_vintage_year': wellpad_vintage_year_col,
        'flares_n': flares_n_col, # Number of flares so far
        'flares_power': flares_power_col, # Total FRP so far
        'n_completions': n_completions_col, # Number of completions so far
        't_comp_diff': t_comp_diff_col, # Days since last completion
        't_spud_diff': t_spud_diff_col, # Days since spud event
        'is_flaring': is_flaring_col, # Is currently flaring
        't_until_next_flare': t_until_next_flare_col, # Y predict
        't_since_last_flare': t_since_last_flare, # Y predict
        'flares_future_n': flares_future_n_col, # Y predict
        'flares_future_power':flares_future_power_col # Y predict
    })

    return [wellpad_code, wellpad_daily_event_df]
        

test_power = np.empty(len(group_keys))

with Pool(4) as p:
    
    for result in list(tqdm(p.imap(process_wellpad_events, range(len(group_keys))), total=len(group_keys), desc='process_wellpad_events')):
        result[1].to_csv(os.path.join('..','..', 'data', 'wellpad_daily_events', str(result[0])+'.csv'), index=False)

process_wellpad_events:   0%|          | 0/54203 [00:00<?, ?it/s]

Process ForkPoolWorker-8:
Process ForkPoolWorker-6:
Process ForkPoolWorker-5:
Process ForkPoolWorker-7:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tmp/ipykernel_44126/2611906541.py", line 58, in process_wellpad_events
    flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring = flare_check(rows, todays_date)
  File "/home/sam/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tmp/ipykernel_44126/2611906541.py", line 58, in process_wellpad_events
    flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring = flare_check(rows, todays_date)
  File "/tmp/ipykernel_44126/2611906541.py", line 58, in process_wellpad_events
    flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring = flare_check(rows, todays_date)
  File "/tmp/ipykernel_44126/4242693684.py", line 13, in flare_check
    rows_today_and_before = rows.loc[rows['aq_date'] <= todays_date] # Get rows today and before
  File "/tmp/ipykernel_44126/2611906541.py", line 58, in process_wellpad_events
    flares_n, flares_power, t_until_next_flare, t_since_last_flare, flares_future_n, flares_future_power, is_flaring = flare_check(rows, todays_date)
  File "/tmp/ipykernel_44126/4242693684.py", line 14, in flare_check
    rows_future = rows.loc[rows['aq_date'] > todays_date] # Get future rows
  File "/tmp/ipykernel_44126/4242693684.py", line 13, in flare_check
    rows_today_and_before = rows.loc[rows['aq_date'] <= todays_date] # Get rows today and before
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/tmp/ipykernel_44126/4242693684.py", line 20, in flare_check
    flares_power = rows_today_and_before.power.sum()
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1104, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 11071, in sum
    return NDFrame.sum(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1104, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1104, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 914, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 10791, in sum
    return self._min_count_stat_function(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 914, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3600, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexing.py", line 914, in _getbool_axis
    return self.obj._take_with_is_copy(inds, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 10773, in _min_count_stat_function
    return self._reduce(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3600, in _take_with_is_copy
    result = self.take(indices=indices, axis=axis)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3586, in take
    new_data = self._mgr.take(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3602, in _take_with_is_copy
    if not result._get_axis(axis).equals(self._get_axis(axis)):
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/series.py", line 4182, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 3586, in take
    new_data = self._mgr.take(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1474, in take
    return self.reindex_indexer(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 4452, in equals
    if self.is_(other):
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 71, in _f
    return f(*args, **kwargs)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1474, in take
    return self.reindex_indexer(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1311, in reindex_indexer
    new_blocks = [
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 556, in is_
    elif not hasattr(other, "_id"):
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 392, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1312, in <listcomp>
    blk.take_nd(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1311, in reindex_indexer
    new_blocks = [
KeyboardInterrupt
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/nanops.py", line 549, in nansum
    values, mask, dtype, dtype_max, _ = _get_values(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 1385, in take_nd
    new_values = algos.take_nd(
  File "/home/sam/anaconda3/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1312, in <listcomp>
    blk.take_nd(

KeyboardInterrupt:

In [ ]:
wellpad_groups.groups.keys()

In [ ]:
t_until_next_flare